### ISSUE TITLE
Candidates for the Logo....

### ISSUE THREAD

**Issue by SirGoodenough** [ikifar2012/amcrest2mqtt-addon#1]
![amcrest2mqtt_candidate2](https://user-images.githubusercontent.com/47349533/156304316-4b7455b7-9e58-4ef1-92d8-f65afe5fdad1.png)
![amcrest2mqtt_candidate1](https://user-images.githubusercontent.com/47349533/156304318-15156ece-d790-4384-8c26-649e31cc2252.png)

**Comment by SirGoodenough** [comment]
[amcrest2mqtt_candidates.tar.zip](https://github.com/ikifar2012/amcrest2mqtt-addon/files/8167160/amcrest2mqtt_candidates.tar.zip)
Forget the zip.  that's just there to allow upload.  It's a tar file of both gimp files.

**Comment by ikifar2012** [comment]
Do you happen to have the originals? whenever I try to edit them they get pixelated

**Comment by SirGoodenough** [comment]
I know what you has said, but just saw this message.
What size are you needing them to be.
I already tossed the originals, but I can work this to the size we need.

**Comment by SirGoodenough** [comment]
[tilde.tar.gz](https://github.com/ikifar2012/amcrest2mqtt-addon/files/8303026/tilde.tar.gz)
Try this.  I built it small 125x125 and the mush is basically gone.
I found a better fitting Amcrest logo from their site.
Sources and gimp, several exported versions.
color is 737373
