### ISSUE TITLE
HTTPError('400 Client Error: Bad Request

### ISSUE THREAD

**Issue by Vendo232** [ikifar2012/amcrest2mqtt-addon#10]
getting this error , also getting like 10 pings per second for this domain from AMCREST doorbell 'drs.zencamcloud.com'

[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
16/02/2023 16:23:18 [INFO] App Version: 1.0.14
16/02/2023 16:23:18 [INFO] Fetching camera details...
16/02/2023 16:23:22 [INFO] Device type: AD110
16/02/2023 16:23:22 [INFO] Serial number: XYZ
16/02/2023 16:23:22 [INFO] Software version: 1.000.00AC009.0.R
16/02/2023 16:23:22 [INFO] Device name: Front_Doorbell_AD110
16/02/2023 16:23:22 [INFO] Writing Home Assistant discovery config...
16/02/2023 16:23:22 [INFO] Fetching storage sensors...
<Front Door:XYZ> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.1.95:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')
<Front Door:XYZ> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.1.95:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')
<Front Door:XYZ> Trying again due to error: HTTPError('400 Client Error: Bad Request for url: http://192.168.1.95:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo')
16/02/2023 16:23:24 [WARNING] Error fetching storage information 400 Client Error: Bad Request for url: http://192.168.1.95:80/cgi-bin/storageDevice.cgi?action=getDeviceAllInfo
16/02/2023 16:23:25 [INFO] Listening for events...

`

![image](https://user-images.githubusercontent.com/44098230/219427121-09818de7-bfa4-422c-905b-5a7af9a2bcfb.png)

**Comment by rabsoft** [comment]
I aqm getting the same issue, also after a period of time it just seems to stop and I have to start it again, even though I have the restart and watchdog enabled

**Comment by ikifar2012** [comment]
t appears the dev that makes amcrest2mqtt seems to have disappeared, https://github.com/dchesterton/amcrest2mqtt/issues/96 and the API seems to have changed. I myself do not have an amcrest device or I would have just forked it and attempted to fix it myself, if anyone knows of a more up to date amcrest2mqtt fork I can base the addon on let me know

**Comment by ikifar2012** [comment]
Please try 2023.3.3 and let me know how it goes
