### ISSUE TITLE
WARNING: MQTT service not available

### ISSUE THREAD

**Issue by raymond-w** [ikifar2012/amcrest2mqtt-addon#15]
After the last update software shuts down with an error

"WARNING: MQTT service not available, please ensure the MQTT Broker addon is installed and configured
Traceback (most recent call last):
  File "/amcrest2mqtt/src/amcrest2mqtt.py", line 1, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
[16:25:17] WARNING: Halt add-on with exit code 1"

MQTT is up and running
HA is on the latest release version
" Home Assistant 2023.3.6
Supervisor 2023.03.2
Operating System 9.5
Frontend 20230309.1 - latest "

**Comment by ikifar2012** [comment]
Please try 2023.3.3 and let me know how it goes

**Comment by ikifar2012** [comment]
Please read:
https://github.com/ikifar2012/amcrest2mqtt-addon/issues/14#issuecomment-1483974994
