### ISSUE TITLE
How can I uninstall amcrest2mqtt?

### ISSUE THREAD

**Issue by JimGermany** [ikifar2012/amcrest2mqtt-addon#7]
I installed the addon v.2022.5.1 and now I try to uninstall. The "normal" way with MQTT Explorer doesn't work. I use MQTT Explorer and deleted the whole Amcrest entry. After that everything seemed fine but after a HA Restart I saw Amcrest Device again under MQTT. 

I have also described the problem with screenshots at: https://community.home-assistant.io/t/delete-mqtt-entities/214100/6 

It would be nice if you could describe the uninstall process. Thanks. :-)

**Comment by SirGoodenough** [comment]
The addon must still be there and running if it recreated the MQTT topic.

Are you sure the Addon is gone?  Not running? Rebooted host after you did that?

Then use MQTT explorer to remove the topics and if it still comes back, something else is re-creating the topic.  We can guess further from there...

**Comment by JimGermany** [comment]
Thanks for the reply. Yes I'm sure it's gone. :-) As you can see in my screenshots https://community.home-assistant.io/t/delete-mqtt-entities/214100/6 after a HA restart or Host reboot I saw Amcrest again under HA Mosquitto broker - MQTT and when i try to delete it then I get "Device/Service not found".

No extra/separately docker only with/over HA Addon.

I think somewhere there has to be an entry in HA itself that keeps re-entering the Amcrest Addon after a reboot/restart. But where (no - not at configuration.yaml)? This entry ensures that it is always re-entered under HA Mosquitto broker, even though there is no longer an entry in the MQTT database.

**Comment by JimGermany** [comment]
Done. There are three hidden sensor entities in the MQTT database. The three entries were not uninstalled during uninstallation. 
So these three entities were reloaded after a HA reboot. I deleted them from the MQTT database and the “spook” was over.
